sudo: required
dist: trusty

jobs:
  include:
  - stage: test
    language: node_js
    node_js: '7'
    install:
    - yarn
    script:
    - yarn ci:travis
    cache:
      directories:
      - node_modules
  - stage: deploy
